app:
    resource: "@AppBundle/Controller/"
    type:     annotation

feedio:
    resource: "@DebrilRssAtomBundle/Resources/config/routing.xml"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

facebook_login:
    pattern: /login/facebook

the:
    resource: "@TheBundle/Resources/config/routing.yml"
    prefix:   /