# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~
        my_custom_hwi_provider:
            id: hwi_oauth.user.provider.entity

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
        secured_area:
            pattern:    ^/
            oauth:
                resource_owners:
                    facebook:      /login_facebook
                    google:        /login_google
                    twitter:       /login_twitter
                login_path:        /
                failure_path:      /login

                oauth_user_provider:
                    service: hwi_oauth.user.provider.entity

            # Turn on anonymous for testings need.
            anonymous: ~